
all:
	make -C libtimer
	make -C libcommon
	make -C libqueue
	make -C libdhcp
	make -C libdctp
	
clean:
	make -C libtimer clean
	make -C libqueue clean
	make -C libdhcp clean
	make -C libdctp clean
	make -C libcommon clean
